SamarthTech/Samarth-Website

css/style.css, index.html
A scroll bar is added to index page.
=> added-scroll-bar-to-index-page

css/style.css, index.html, js/3-scroll-top.js
Added a scroll to top button to index page
=> added-back-to-top-button-to-index

css/style.css, index.html, js/pre.js
new loader added to index page
=> new-loader

css/style.css, index.html
2 changes committed 
1. Loader modification added to existing version of index.
2. Curser-pointer modifications done.
=> loader-pointer-modified

css/style.css, js/getResource.js, js/index.js, resource.html
Issues:
1. buttons appearing after first click
=> resource-page-2.0-added

resource.html
labels and sub-labels updated as per last meeting.
=> labels changed

css/style.css, js/getResource.js
Images of tables of exam pattern in UPSC-ESE in resource.html are made responsive.
=> tables made responsive

resource.html
=> sample-comment-added

css/style.css, index.html
#41 Fixed the issue do alert me in case of any discrepancies and if pr is accepted do add hacktoberfest labels. Thank You!!
=> Fixed the size of Guest Cards.

css/style.css, js/main.js
- Change menu toggler icon on opening/closing menu
- Removed outline on menu toggler focus
=> Fixed issue #40 - Improve UI of opened menu in mobile screens

contact.html, events.html, index.html, resource.html, team.html
Resource page added for further updates in Hacktoberfest.
=> resource-page-going-live

css/style.css, index.html
=> adjust get in touch btn

contact.html, css/style.css, events.html, resource.html, team.html
These are the changes corresponding to PR #64 . Errors related to navigation bar in all the pages have been fixed and the resource page opening message is also modified.
=> Bugs and Errors fixed

css/style.css, resource.html
=> changes made

resource.html
Solved footer issues
Fixes issue #70
=> Updated resource.html

events.html, index.html
=> Fix : 'Get in Touch' Button [fixes #69]

.vscode/settings.json, css/footer.css, index.html
I have styled the social media icons , plz review it and add hacktoberfest tag
=> social media icons styling done

contact.html, css/footer.css, css/style.css, events.html, index.html, resource.html, team.html
I have Styled the Social media presence on all pages and the white space below the footer was also removed ..
=> styling of social icons done in all pages and white space removed

contact.html, events.html, index.html, resource.html, sponsor.html, team.html
First version of sponsor page added. Navigation Bar of all the pages modified.
=> added sponsor page and updated navbar on all pages

css/style.css, js/getResource.js
=> to be updated soon text changed

crregister.html
=> add form validation
